FROM alpine:latest

RUN apk add --no-cache \
    bash \
    ca-certificates \
    curl \
    git \
    openssh-client \
    openrc \
    tzdata && \
    mkdir -p /workspace

WORKDIR /workspace

CMD ["/sbin/init"]
