PubkeyAuthentication yes
AuthorizedKeysCommand /usr/local/bin/macos-authorized-keys %u
AuthorizedKeysCommandUser root

PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
X11Forwarding no
